# Generated by Django 3.1 on 2020-08-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='content_presentation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
