# Generated by Django 3.1 on 2020-08-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_company_content_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='test',
            field=models.TextField(null=True),
        ),
    ]
