# Generated by Django 3.1 on 2020-08-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_company_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='content_presentation',
        ),
        migrations.RemoveField(
            model_name='company',
            name='test',
        ),
    ]
