# Generated by Django 3.1 on 2020-08-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200821_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='content_presentation',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
