# Generated by Django 3.1 on 2020-08-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_company_content_presentation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'cie'},
        ),
        migrations.AddField(
            model_name='company',
            name='photo',
            field=models.ImageField(default='', upload_to='./static/img'),
        ),
    ]
