# Generated by Django 3.1 on 2020-08-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200822_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Compagnies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(default='', upload_to='galery'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content_presentation', models.CharField(default='SOME STRING', max_length=100)),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(default='', upload_to='galery')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company')),
            ],
            options={
                'verbose_name': 'Products',
            },
        ),
    ]
