# Generated by Django 3.1 on 2020-08-27 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200823_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonbon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content_presentation', models.CharField(default='SOME STRING', max_length=100)),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(default='', upload_to='galery')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company')),
            ],
            options={
                'verbose_name': 'Products',
            },
        ),
    ]
