# Generated by Django 3.1 on 2020-08-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bonbon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonbon',
            options={'verbose_name': 'Bonbon'},
        ),
    ]
