# Generated by Django 3.1 on 2020-08-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200827_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bonbon',
        ),
    ]
